name: Generate file index
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 18 * * *'   # JST 03:00

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python scripts/generate_all_files_index.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: all_files_index
          path: all_files_index.json
          if-no-files-found: error
